## Cosas ha hacer: ##
1. Integracion: 
    - Obtención de datos: OK
    - Explicación del dataset: OK
    - Resolver duplicidades e incosistencias. 
    - Resolver problemas de codificacion (unidades de medida Km, m).
2. Preprocesamiento:
    - Outliers: OK.
    - Valores faltantes: OK.(Obtener por la mediana o por algun metodo REV).
    - Normalizar: No es necesario ya que con el tratamiento de los outliers los valores son manejables.
    - Discretizar
    - Selección/Reducción de variables.
3. Modelo: (Conjunto Entrenamiento, Test y Validación)
    - KNN.
    - Regresión lógistica. (Filtros ruido TOMEK LINKS, CVCF)
    - Arboles.
4. Evalución: Metodologias dividir datos entrenamiento, validacion y test
    - Matriz de confusión.
    - Clasificacion precision predictiva(Usando Grid).
    - Error cuadratico medio.
5. Interpretación y difusión:
    - Usos del modelo.



## Proyecto Final
- Yeray Aller Errea
- Javier Aranguren Ortiz
### Resumen
El objetivo de nuestro grupo va a ser utilizar las distintas herramientas que nos proporciona esta asignatura para identificar que tipo de trigo es.

### Desarrollo
![Descripción KDD](KDD.jpg)  
Para este proyeto vamos a utilizar la metodología KDD, que se divide en la siguientes etapas
1. Integracion y recopilacion.
2. Preprocesamiento.
3. Modelado.
4. Evalución.
5. Disfusiónn.


## INTEGRACIÓN Y RECOPILACIÓN ##
### Dataset ###
Para ese proyecto hemos seleccionado el dataset [Seeds](https://www.kaggle.com/datasets/rwzhang/seeds-dataset).El conjunto de datos Seeds contiene siete atributos geométricos de granos de trigo, y hay tres variedades de trigo.
- Área del grano **A**
- Perímetro del grano **P**
- Compacidad del grano **C** = 4 * pi * A / P^2
- Longitud del núcleo
- Ancho del núcleo
- Coeficiente de asimetría
- Longitud del surco del núcleo

### Librerias ###
Para el siguiente proyecto hemos usado las siguientes librerias:
- Pandas.
- Numpy.
- Sekelearn.

In [1]:
##Importamos todas las librerias necesarias para la práctica
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.base import TransformerMixin
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

### Carga de datos ###
La información necesaria para este proyecto se encuentra seed_dataset.txt, la extraemos y la almacenamos.

In [2]:
# Lectura del archivo csv
seeds = pd.read_csv('seeds_dataset.txt', delim_whitespace=True, header=None)
# Asignamos los nombres de las columnas
seeds.columns = ['area', 'perimetro', 'compacidad', 'longitud_nucleo', 'ancho_nucleo', 'coeficiente_asimetria', 'longitud_surco', 'class']
seeds

area  perimetro  compacidad  longitud_nucleo  ancho_nucleo  \
0    15.26      14.84      0.8710            5.763         3.312   
1    14.88      14.57      0.8811            5.554         3.333   
2    14.29      14.09      0.9050            5.291         3.337   
3    13.84      13.94      0.8955            5.324         3.379   
4    16.14      14.99      0.9034            5.658         3.562   
..     ...        ...         ...              ...           ...   
205  12.19      13.20      0.8783            5.137         2.981   
206  11.23      12.88      0.8511            5.140         2.795   
207  13.20      13.66      0.8883            5.236         3.232   
208  11.84      13.21      0.8521            5.175         2.836   
209  12.30      13.34      0.8684            5.243         2.974   

     coeficiente_asimetria  longitud_surco  class  
0                    2.221           5.220      1  
1                    1.018           4.956      1  
2                    2.699           4.825      1  
3                    2.259           4.805      1  
4                    1.355           5.175      1  
..                     ...             ...    ...  
205                  3.631           4.870      3  
206                  4.325           5.003      3  
207                  8.315           5.056      3  
208                  3.598           5.044      3  
209                  5.637           5.063      3  

[210 rows x 8 columns]

## Preprocesamiento ##

Comprobamos si hay alguna fila que tenga la columna class vacia y la tratamos

In [3]:
def esNulo(dataset):
    if(dataset["class"].isnull().sum()==0):
        print("No hay clases sin valor")
    else:
        print("Hay clases sin valor")
    
print(esNulo(seeds))

No hay clases sin valor
None


Comprobamos si existen duplicidades o inconsistencias y las tratamos.

In [4]:
if(seeds.duplicated().any()):
    seeds.drop_duplicates()
    print("Duplicidades eliminadas")
else:
    print("No existen duplicidades")

No existen duplicidades


Generamos dos DataFrames: uno para la información de entrada (X) y otro para la de salida (y)

In [5]:
X = seeds.iloc[:, :-1]
y = seeds.iloc[:, -1]

A continuación vamos a dividir los ejemplos en train, validación y test utilizando Hold-out con estratificación y el valor 42 como semilla.

Vamos a dividir los conjuntos en un 10% test, 80% entrenamiento y el restante validacion.

In [6]:
X_resto, X_test, y_resto, y_test = train_test_split(X, y, test_size=0.1, stratify=y, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_resto, y_resto, test_size=0.2, stratify=y_resto, random_state=42)

Creamos la clase de detección y tratamiento de Outliers

In [7]:
class OutlierDetecion_treatment_IQR(TransformerMixin):

    # Constructor de la clase
    def __init__(self, k=1.5, columns=None):
        self.k = k
        self.columns = columns
    
    # Método fit
    def fit(self, X, y=None):
        # Transformamos X a DataFrame por si llega un array de Numpy (para compatibilidad en la Pipeline)
        X = pd.DataFrame(X)
        if self.columns == None:
            # Si no se determinan variables en el constructor si tratan todas
            self.columns = X.columns
            #self.stats = <RELLENAR>
            self.stats = X.describe()
        # Devolvemos el propio objeto modificado
        return self

    # Método transform
    def transform(self, X):
        # Transformamos X a DataFrame por si llega un array de Numpy (para compatibilidad en la Pipeline)
        X = pd.DataFrame(X)
        # Creamos una copia del DataFrame X para no perder los datos originales
        Xaux = X.copy()
        # Se calula el IQR de cada variable
        IQRs = self.stats.loc['75%'] - self.stats.loc['25%']
        # Se calculan los límites inferiores y superiores   
        limiteInf = self.stats.loc['25%'] - self.k * IQRs
        limiteSup = self.stats.loc['75%'] + self.k * IQRs
        # Se comprueba qué elementos están por encima y por debajo de dichos límites (máscaras de booleanos)  
        menores = (X < limiteInf)
        mayores = (X > limiteSup)
        # Se recorren las variables para detectar outliers y tratarlos (sustituir por la mediana de la variable)
        for c in self.columns:
            # obtenemos la lista de booleanos correspondientes a si los valores de los ejemplos son outliers o no para la variable c
            indices = np.logical_or(menores[c], mayores[c])
            # Si hay outliers
            if indices.any():
                # Los sustituimos por la mediana
                Xaux.loc[indices,c] = self.stats.loc['50%',c]
        # Se devuelve el DataFrame modificado
        return Xaux
    
    # Método para asignar los valores de los híper-parámetros y que, de este modo, 
        # podamos aplicar GridSearchCV sobre un objeto de esta clase
    def set_params(self, **parameters):
        for parameter, value in parameters.items():
            setattr(self, parameter, value)
        return self
    
    # Método para obtener los valores de los híper-parámetros que queramos del modelo (lo usa GridSearchCV al mostrar la mejor configuración)
    def get_params(self, deep=True):
        # Devolvemos los valores de los híper-parámetros del método de preparación de datos
        return {"k": self.k}

In [8]:
out_IQR = OutlierDetecion_treatment_IQR(k=3)
X_train_IQR = out_IQR.fit_transform(X_train)
if(X_train.equals(X_train_IQR)):
   print("No se han encontrado outliers")
else:
   print("Se han encontrado outliers y el dataframe ha sido modificado")

No se han encontrado outliers


Ahora vamos a utilizar diferentes tecnicas de clasificacion para evaluar sus rendimientos.
### KNN ###

In [9]:
param_grid = {
    'n_neighbors': [3, 5, 7, 9],
    'weights': ['uniform', 'distance'],
    'p': [1, 2, 1.5, 3]
}

grid_KNN = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5)
grid_KNN.fit(X_train, y_train)
prediccion_KNN = grid_KNN.predict(X_test)
accuracy = accuracy_score(y_test, prediccion_KNN) * 100

print("Mejores hiperparámetros:", grid_KNN.best_params_)
print("Best score: {:.2f}%".format(grid_KNN.best_score_ * 100))
print("Precisión: {:.2f}%".format(accuracy))

Mejores hiperparámetros: {'n_neighbors': 5, 'p': 1.5, 'weights': 'distance'}
Best score: 95.40%
Precisión: 85.71%


In [10]:
knn = KNeighborsClassifier(3)
knn.fit(X_train, y_train)
prediccion_KNN2 = knn.predict(X_train)

### Regresion ###

In [11]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
prediccion = lr.predict(X_test)
accuracy = accuracy_score(y_test, prediccion) * 100
print("Precisión: {:.2f}%".format(accuracy))

Precisión: 90.48%


### Arboles de decision ###

In [12]:
tree = DecisionTreeClassifier(random_state=42)
tree.fit(X_train, y_train)
prediccion_arbol = tree.predict(X_test)
accuracy = accuracy_score(y_test, prediccion_arbol) * 100
print('Precisión del árbol de decisión: {:.2f}%'.format(accuracy))

Precisión del árbol de decisión: 95.24%


## Evaluacion ##

### Matriz de Confusión ###

In [17]:
def obtenerMatrizConfusion(clasificador, X, y, labels):
    predicciones = clasificador.predict(X)
    return confusion_matrix(y, predicciones, labels=labels)
# Creo un clasificador que siempre clasifique negativo
matrizConfusionKNN = obtenerMatrizConfusion(grid_KNN, X_train, y_train, labels=[1,2,3])
matrizConfusionLR = obtenerMatrizConfusion(lr, X_train, y_train, labels=[1,2,3])
matrizConfusionTREE = obtenerMatrizConfusion(tree, X_train, y_train, labels=[1,2,3])
print(matrizConfusionKNN)
print(matrizConfusionLR)
print(matrizConfusionTREE)

[[51  0  0]
 [ 0 50  0]
 [ 0  0 50]]
[[47  2  2]
 [ 3 47  0]
 [ 2  0 48]]
[[51  0  0]
 [ 0 50  0]
 [ 0  0 50]]
